Description :
The dataset is a .csv file that contain the information about various application on the playstore.
We have to perform analysis on it.


Dataset: https://drive.google.com/file/d/1mVdEdPMIcWYHU0cN-HmaI0doM7xQSmAV/view?usp=sharing

# Importing the Libraries

In [1]:
# For mathematical operations
import numpy as np

# For data analysis
import pandas as pd

# For data cleaning
import re

# For data visualization
import matplotlib.pyplot as plt

# For data visualization
import seaborn as sns

# Loading the dataset

In [2]:
mobile = pd.read_csv("/content/drive/MyDrive/ayush/Project-5 Mobile Application Dataset/Mobile_Applications.csv")

# Data Exploration

In [3]:
# Firts five rows of ath datafram3
mobile.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [4]:
# Bottom five rows of dataframe
mobile.tail()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [5]:
# Creating a copy of the DataFrame. So our original data will remain safe.
mob = mobile.copy()

In [6]:
# Show all the columns in the Dataframe
mob.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [7]:
# Total number of columns
len(mob.columns)

13

In [8]:
# Shape of mob Dataframe
mob.shape

(10841, 13)

In [9]:
# General information of dataframe
mob.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [10]:
# Statistical information of dataframe
mob.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [11]:
# Checking for total no. of null values in all columns
mob.isna().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [12]:
# row having the null ration 
mob[mob.Type.isna()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
9148,Command & Conquer: Rivals,FAMILY,NaN,0,Varies with device,0,NaN,0,Everyone 10+,Strategy,"June 28, 2018",Varies with device,Varies with device

In [13]:
# Change the name of the column 'App' to 'App_name'
mob.rename(columns = {'App':'App_name'}, inplace = True)

In [14]:
# All the unique values in Category column
mob.Category.unique()

array(['ART_AND_DESIGN', 'AUTO_AND_VEHICLES', 'BEAUTY',
       'BOOKS_AND_REFERENCE', 'BUSINESS', 'COMICS', 'COMMUNICATION',
       'DATING', 'EDUCATION', 'ENTERTAINMENT', 'EVENTS', 'FINANCE',
       'FOOD_AND_DRINK', 'HEALTH_AND_FITNESS', 'HOUSE_AND_HOME',
       'LIBRARIES_AND_DEMO', 'LIFESTYLE', 'GAME', 'FAMILY', 'MEDICAL',
       'SOCIAL', 'SHOPPING', 'PHOTOGRAPHY', 'SPORTS', 'TRAVEL_AND_LOCAL',
       'TOOLS', 'PERSONALIZATION', 'PRODUCTIVITY', 'PARENTING', 'WEATHER',
       'VIDEO_PLAYERS', 'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION',
       '1.9'], dtype=object)

In [15]:
# Total no. of unique values on Category column
mob.Category.nunique()

34

In [16]:
# Minimum value in Rating column
mob.Rating.min()

1.0

In [17]:
# Maximum value in Rating column
mob.Rating.max()

19.0

In [18]:
# Row in the mob dataframe where rating is 19.0
mob[mob['Rating'] == 19.0]

,App_name,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [19]:
# We have observed that for the row having the index as 10472 the Category column contain the value of Rating Column , Rating column contain the value of Review column and so no..
# So the fix this we have shifted the values 
mob.iloc[10472,:]

App_name          Life Made WI-Fi Touchscreen Photo Frame
Category                                              1.9
Rating                                               19.0
Reviews                                              3.0M
Size                                               1,000+
Installs                                             Free
Type                                                    0
Price                                            Everyone
Content Rating                                        NaN
Genres                                  February 11, 2018
Last Updated                                       1.0.19
Current Ver                                    4.0 and up
Android Ver                                           NaN
Name: 10472, dtype: object

In [20]:
mob.iloc[10472,1:]

Category                        1.9
Rating                         19.0
Reviews                        3.0M
Size                         1,000+
Installs                       Free
Type                              0
Price                      Everyone
Content Rating                  NaN
Genres            February 11, 2018
Last Updated                 1.0.19
Current Ver              4.0 and up
Android Ver                     NaN
Name: 10472, dtype: object

In [21]:
mob.iloc[10472,1:] = mob.iloc[10472,1:].shift()

In [22]:
mob.iloc[10472,:]

App_name          Life Made WI-Fi Touchscreen Photo Frame
Category                                             None
Rating                                                1.9
Reviews                                              19.0
Size                                                 3.0M
Installs                                           1,000+
Type                                                 Free
Price                                                   0
Content Rating                                   Everyone
Genres                                                NaN
Last Updated                            February 11, 2018
Current Ver                                        1.0.19
Android Ver                                    4.0 and up
Name: 10472, dtype: object

In [23]:
mob.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App_name        10841 non-null  object
 1   Category        10840 non-null  object
 2   Rating          9367 non-null   object
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10841 non-null  object
 9   Genres          10840 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10839 non-null  object
dtypes: object(13)
memory usage: 1.1+ MB

In [24]:
# Converting the datatype of Rating column to float
mob['Rating'] = mob['Rating'].astype("float")

In [25]:
mob.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App_name        10841 non-null  object
 1   Category        10840 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10841 non-null  object
 9   Genres          10840 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10839 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [26]:
# Checking for the hightest Rating
mob.sort_values('Rating',ascending=False)

,App_name,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
9056,Santa's Monster Shootout DX,GAME,5.0,4,33M,50+,Paid,$1.99,Teen,Action,"August 15, 2013",1.05,2.2 and up
8395,DG TV,NEWS_AND_MAGAZINES,5.0,3,5.7M,100+,Free,0,Everyone,News & Magazines,"May 26, 2018",1.2,4.1 and up
8493,PK and DK Audio App,FAMILY,5.0,2,3.9M,100+,Free,0,Everyone,Entertainment,"October 25, 2017",5.1.4,4.1 and up
6330,HON. B.J. ACS COLLEGE ALE,FAMILY,5.0,3,1.8M,100+,Free,0,Mature 17+,Education,"December 26, 2016",3.1,4.3 and up
6342,BJ Foods,BUSINESS,5.0,3,1.5M,10+,Free,0,Everyone,Business,"February 7, 2018",2.7,4.1 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10824,Cardio-FR,MEDICAL,NaN,67,82M,"10,000+",Free,0,Everyone,Medical,"July 31, 2018",2.2.2,4.4 and up
10825,Naruto & Boruto FR,SOCIAL,NaN,7,7.7M,100+,Free,0,Teen,Social,"February 2, 2018",1.0,4.0 and up
10831,payermonstationnement.fr,MAPS_AND_NAVIGATION,NaN,38,9.8M,"5,000+",Free,0,Everyone,Maps & Navigation,"June 13, 2018",2.0.148.0,4.0 and up
10835,FR Forms,BUSINESS,NaN,0,9.6M,10+,Free,0,Everyone,Business,"September 29, 2016",1.1.5,4.0 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up

In [27]:
mob.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App_name        10841 non-null  object
 1   Category        10840 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10841 non-null  object
 9   Genres          10840 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10839 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [28]:
# App_name where the category is null
mob['App_name'][mob['Category'].isna()]

10472    Life Made WI-Fi Touchscreen Photo Frame
Name: App_name, dtype: object

In [29]:
mob.Category.unique()

array(['ART_AND_DESIGN', 'AUTO_AND_VEHICLES', 'BEAUTY',
       'BOOKS_AND_REFERENCE', 'BUSINESS', 'COMICS', 'COMMUNICATION',
       'DATING', 'EDUCATION', 'ENTERTAINMENT', 'EVENTS', 'FINANCE',
       'FOOD_AND_DRINK', 'HEALTH_AND_FITNESS', 'HOUSE_AND_HOME',
       'LIBRARIES_AND_DEMO', 'LIFESTYLE', 'GAME', 'FAMILY', 'MEDICAL',
       'SOCIAL', 'SHOPPING', 'PHOTOGRAPHY', 'SPORTS', 'TRAVEL_AND_LOCAL',
       'TOOLS', 'PERSONALIZATION', 'PRODUCTIVITY', 'PARENTING', 'WEATHER',
       'VIDEO_PLAYERS', 'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION', None],
      dtype=object)

In [30]:
mob.head(1)

,App_name,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up

In [31]:
a = str(mob['App_name'][mob['Category'].isna()]).upper().split()[1:7]
a

['LIFE', 'MADE', 'WI-FI', 'TOUCHSCREEN', 'PHOTO', 'FRAME']

In [32]:
cat=[]
for i in a:
  for j,k in zip(mob.App_name, mob.Category):
    if i in j.upper():
      print(f'App: {j} & Category: {k}')
      cat.append(str(k))

App: Hojiboy Tojiboyev Life Hacks & Category: COMICS
App: Cougar Dating Life : Date Older Women Sugar Mummy & Category: DATING
App: Cougar Dating Life : Date Older Women Sugar Mummy & Category: DATING
App: Udacity - Lifelong Learning & Category: EDUCATION
App: Udacity - Lifelong Learning & Category: EDUCATION
App: My Study Life - School Planner & Category: EDUCATION
App: Toca Life: City & Category: EDUCATION
App: Toca Life: Hospital & Category: EDUCATION
App: Lifetime - Watch Full Episodes & Original Movies & Category: ENTERTAINMENT
App: Lifetime - Watch Full Episodes & Original Movies & Category: ENTERTAINMENT
App: Lifetime - Watch Full Episodes & Original Movies & Category: ENTERTAINMENT
App: MeAuDote - An act of love that saves a life & Category: EVENTS
App: Endurance Lifestyle & Category: EVENTS
App: Eternal life & Category: LIBRARIES_AND_DEMO
App: The Game of Life & Category: GAME
App: Moana Island Life & Category: FAMILY
App: Toca Life: City & Category: FAMILY
App: Barbie Life™ & Category: FAMILY
App: BioLife Plasma Services & Category: MEDICAL
App: HealtheLife & Category: MEDICAL
App: Life market & Category: SHOPPING
App: lifebox & Category: PRODUCTIVITY
App: The first year of a baby's life & Category: PARENTING
App: What was I in my Past Life & Category: FAMILY
App: AT&T Digital Life & Category: LIFESTYLE
App: Jurassic Life: T Rex Simulator & Category: FAMILY
App: The Aether: Life as a God & Category: FAMILY
App: Avakin Life - 3D virtual world & Category: FAMILY
App: Brilliant Quotes: Life, Love, Family & Motivation & Category: BOOKS_AND_REFERENCE
App: BW SmartLife & Category: TOOLS
App: CB SMART LIFE & Category: TOOLS
App: CF Life & Category: FAMILY
App: CK Life & Category: HEALTH_AND_FITNESS
App: FML F*ck my life + widget & Category: FAMILY
App: Battery Doctor-Battery Life Saver & Battery Cooler & Category: TOOLS
App: StudentLife.com.cy & Category: NEWS_AND_MAGAZINES
App: Thuglife Video Maker & Category: FAMILY
App: DG Smart life & Category: TOOLS
App: MyLifeOrganized: To-Do List & Category: PRODUCTIVITY
App: DP Display Pictures Life Quotes Motivational GM & Category: SOCIAL
App: DU Battery Saver - Battery Charger & Battery Life & Category: TOOLS
App: MelifeCam-M & Category: VIDEO_PLAYERS
App: EG Way Life & Category: SOCIAL
App: The Game of Life & Category: GAME
App: Lifeguard Beach Rescue ER Emergency Hospital Games & Category: FAMILY
App: EU Life Explorer & Category: NEWS_AND_MAGAZINES
App: S.O.L : Stone of Life EX & Category: FAMILY
App: studentsLife by FH Kärnten & Category: FAMILY
App: Life Made WI-Fi Touchscreen Photo Frame & Category: None
App: LifePoint Church - FL & Category: LIFESTYLE
App: Current debit card and app made for teens & Category: FINANCE
App: Recipes Pastries and homemade pies More than 500 recipes for pastries & Category: FOOD_AND_DRINK
App: mySugr: the blood sugar tracker made just for you & Category: MEDICAL
App: mySugr: the blood sugar tracker made just for you & Category: MEDICAL
App: Wish - Shopping Made Fun & Category: SHOPPING
App: Wish - Shopping Made Fun & Category: SHOPPING
App: Wish - Shopping Made Fun & Category: SHOPPING
App: Zappos – Shoe shopping made simple & Category: SHOPPING
App: Etsy: Handmade & Vintage Goods & Category: SHOPPING
App: Zappos – Shoe shopping made simple & Category: SHOPPING
App: Etsy: Handmade & Vintage Goods & Category: SHOPPING
App: Wish - Shopping Made Fun & Category: SHOPPING
App: Baby Food - Homemade Recipes & Category: PARENTING
App: Wish - Shopping Made Fun & Category: SHOPPING
App: V Made & Category: BOOKS_AND_REFERENCE
App: mySugr: the blood sugar tracker made just for you & Category: MEDICAL
App: Amadeus GR & CY & Category: COMMUNICATION
App: DQSalmaan - A fan made App & Category: FAMILY
App: Life Made WI-Fi Touchscreen Photo Frame & Category: None
App: AT&T Smart Wi-Fi & Category: TOOLS
App: Hotspot Shield Free VPN Proxy & Wi-Fi Security & Category: TOOLS
App: osmino Wi-Fi: free WiFi & Category: TOOLS
App: Portable Wi-Fi hotspot & Category: COMMUNICATION
App: USB BT Wi-Fi Color Terminal Modem & Category: TOOLS
App: Wi-Fi Auto-connect & Category: COMMUNICATION
App: Smart Wi-Fi Hotspot PRO & Category: COMMUNICATION
App: Talkie - Wi-Fi Calling, Chats, File Sharing & Category: COMMUNICATION
App: Portable Wi-Fi hotspot Premium & Category: COMMUNICATION
App: Avast Wi-Fi Finder & Category: PRODUCTIVITY
App: WeFi - Free Fast WiFi Connect & Find Wi-Fi Map & Category: COMMUNICATION
App: Talkie Pro - Wi-Fi Calling, Chats, File Sharing & Category: COMMUNICATION
App: Safe Wi-Fi & Category: PRODUCTIVITY
App: WiFi Monitor Pro - analyzer of Wi-Fi networks & Category: TOOLS
App: Wi-Fi Rabbit Unlock Key & Category: TOOLS
App: Wi-Fi settings shortcut & Category: TOOLS
App: Wi-Fi Master & Category: TOOLS
App: Portable Wi-Fi hotspot Free & Category: COMMUNICATION
App: Wi-Fi Networks & Category: PRODUCTIVITY
App: TownWiFi | Wi-Fi Everywhere & Category: COMMUNICATION
App: Jazz Wi-Fi & Category: COMMUNICATION
App: Xposed Wi-Fi-Pwd & Category: PERSONALIZATION
App: Life Made WI-Fi Touchscreen Photo Frame & Category: None
App: osmino Wi-Fi: free WiFi & Category: TOOLS
App: Wi-Fi Visualizer & Category: TOOLS
App: Lennox iComfort Wi-Fi & Category: LIFESTYLE
App: Free Wi-fi HotspoT & Category: COMMUNICATION
App: Life Made WI-Fi Touchscreen Photo Frame & Category: None
App: Photo Editor & Candy Camera & Grid & ScrapBook & Category: ART_AND_DESIGN
App: Smoke Effect Photo Maker - Smoke Editor & Category: ART_AND_DESIGN
App: Text on Photo - Fonteee & Category: ART_AND_DESIGN
App: Name Art Photo Editor - Focus n Filters & Category: ART_AND_DESIGN
App: Tattoo Name On My Photo Editor & Category: ART_AND_DESIGN
App: Photo Designer - Write your name with shapes & Category: ART_AND_DESIGN
App: Boys Photo Editor - Six Pack & Men's Suit & Category: ART_AND_DESIGN
App: Animated Photo Editor & Category: ART_AND_DESIGN
App: Sad Poetry Photo Frames 2018 & Category: ART_AND_DESIGN
App: Textgram - write on photos & Category: ART_AND_DESIGN
App: BestCam Selfie-selfie, beauty camera, photo editor & Category: BEAUTY
App: Selfie Camera Photo Editor & Filter & Sticker & Category: BEAUTY
App: Photo Editor 2018 & Category: BEAUTY
App: Funny Jokes Photos & Category: COMICS
App: i miss you quotes and photos & Category: DATING
App: PTI Flex Maker, Photo Frame Editor & Songs 2018 & Category: EVENTS
App: Picktrainer: India's largest photo contest app & Category: EVENTS
App: MealLogger-Photo Food Journal & Category: HEALTH_AND_FITNESS
App: MealLogger-Photo Food Journal & Category: HEALTH_AND_FITNESS
App: Viva Decora - Decoration, Photos, Architecture, House & Category: HOUSE_AND_HOME
App: Hide Something - Photo, Video & Category: SOCIAL
App: Frontback - Social Photos & Category: SOCIAL
App: uCiC- Videos and Photos on demand & Category: SOCIAL
App: Shutterfly: Free Prints, Photo Books, Cards, Gifts & Category: PHOTOGRAPHY
App: FreePrints – Free Photos Delivered & Category: PHOTOGRAPHY
App: Groovebook Photo Books & Gifts & Category: PHOTOGRAPHY
App: Moony Lab - Print Photos, Books & Magnets ™ & Category: PHOTOGRAPHY
App: LALALAB prints your photos, photobooks and magnets & Category: PHOTOGRAPHY
App: Google Photos & Category: PHOTOGRAPHY
App: LightX Photo Editor & Photo Effects & Category: PHOTOGRAPHY
App: Sweet Snap - live filter, Selfie photo edit & Category: PHOTOGRAPHY
App: Adobe Photoshop Express:Photo Editor Collage Maker & Category: PHOTOGRAPHY
App: HD Camera - Quick Snap Photo & Video & Category: PHOTOGRAPHY
App: Waterfall Photo Frames & Category: PHOTOGRAPHY
App: Photo frame & Category: PHOTOGRAPHY
App: Unicorn Photo & Category: PHOTOGRAPHY
App: Makeup Editor -Beauty Photo Editor & Selfie Camera & Category: PHOTOGRAPHY
App: Makeup Photo Editor: Makeup Camera & Makeup Editor & Category: PHOTOGRAPHY
App: Moto Photo Editor & Category: PHOTOGRAPHY
App: Garden Photo Frames - Garden Photo Editor & Category: PHOTOGRAPHY
App: Photo Frame & Category: PHOTOGRAPHY
App: Selfie Camera - Photo Editor & Filter & Sticker & Category: PHOTOGRAPHY
App: Sweet Snap Lite - live filter, Selfie photo editor & Category: PHOTOGRAPHY
App: Selfie Camera: Beauty Camera, Photo Editor,Collage & Category: PHOTOGRAPHY
App: Night Photo Frame & Category: PHOTOGRAPHY
App: Selfie Photo Editor & Category: PHOTOGRAPHY
App: BeautyPlus - Easy Photo Editor & Selfie Camera & Category: PHOTOGRAPHY
App: My Photo Keyboard & Category: PHOTOGRAPHY
App: Kids Photo Frames & Category: PHOTOGRAPHY
App: Pencil Photo Sketch-Sketching Drawing Photo Editor & Category: PHOTOGRAPHY
App: Pretty Makeup, Beauty Photo Editor & Snappy Camera & Category: PHOTOGRAPHY
App: Photo Collage - Layout Editor & Category: PHOTOGRAPHY
App: Photo Frames & Category: PHOTOGRAPHY
App: Sweet Selfie - selfie camera, beauty cam, photo edit & Category: PHOTOGRAPHY
App: Candy selfie - photo editor, live filter camera & Category: PHOTOGRAPHY
App: YouCam Perfect - Selfie Photo Editor & Category: PHOTOGRAPHY
App: Beauty Makeup – Photo Makeover & Category: PHOTOGRAPHY
App: Blur Image Background Editor (Blur Photo Editor) & Category: PHOTOGRAPHY
App: Google Photos & Category: PHOTOGRAPHY
App: Muzy - Share photos & collages & Category: PHOTOGRAPHY
App: QuickPic - Photo Gallery with Google Drive Support & Category: PHOTOGRAPHY
App: Shutterfly: Free Prints, Photo Books, Cards, Gifts & Category: PHOTOGRAPHY
App: Photo Editor Selfie Camera Filter & Mirror Image & Category: PHOTOGRAPHY
App: BeautyPlus - Easy Photo Editor & Selfie Camera & Category: PHOTOGRAPHY
App: Photo Mixer & Category: PHOTOGRAPHY
App: Photo Editor- & Category: PHOTOGRAPHY
App: Cymera Camera- Photo Editor, Filter,Collage,Layout & Category: PHOTOGRAPHY
App: YouCam Perfect - Selfie Photo Editor & Category: PHOTOGRAPHY
App: LINE Camera - Photo editor & Category: PHOTOGRAPHY
App: InstaSize Photo Filters & Collage Editor & Category: PHOTOGRAPHY
App: KVAD Camera +: Selfie, Photo Filter, Grids & Category: PHOTOGRAPHY
App: Candy Camera - selfie, beauty camera, photo editor & Category: PHOTOGRAPHY
App: Photo Editor & Category: PHOTOGRAPHY
App: Camera360: Selfie Photo Editor with Funny Sticker & Category: PHOTOGRAPHY
App: Mega Photo & Category: PHOTOGRAPHY
App: Google Photos & Category: PHOTOGRAPHY
App: Muzy - Share photos & collages & Category: PHOTOGRAPHY
App: QuickPic - Photo Gallery with Google Drive Support & Category: PHOTOGRAPHY
App: Shutterfly: Free Prints, Photo Books, Cards, Gifts & Category: PHOTOGRAPHY
App: SuperPhoto - Effects & Filters & Category: PHOTOGRAPHY
App: Photo Editor Pro & Category: PHOTOGRAPHY
App: Beauty Makeup Snappy Collage Photo Editor - Lidow & Category: PHOTOGRAPHY
App: Square InPic - Photo Editor & Collage Maker & Category: PHOTOGRAPHY
App: Cymera Camera- Photo Editor, Filter,Collage,Layout & Category: PHOTOGRAPHY
App: Camera MX - Free Photo & Video Camera & Category: PHOTOGRAPHY
App: EyeEm - Camera & Photo Filter & Category: PHOTOGRAPHY
App: Candy Camera - selfie, beauty camera, photo editor & Category: PHOTOGRAPHY
App: Camera360: Selfie Photo Editor with Funny Sticker & Category: PHOTOGRAPHY
App: PhotoWonder: Pro Beauty Photo Editor Collage Maker & Category: PHOTOGRAPHY
App: Photo Effects Pro & Category: PHOTOGRAPHY
App: Photo Editor Selfie Camera Filter & Mirror Image & Category: PHOTOGRAPHY
App: Photo Studio & Category: PHOTOGRAPHY
App: Photo Editor Pro & Category: PHOTOGRAPHY
App: FilterGrid - Cam&Photo Editor & Category: PHOTOGRAPHY
App: Photo Editor- & Category: PHOTOGRAPHY
App: Mirror Photo:Editor Collage (HD) & Category: PHOTOGRAPHY
App: PhotoDirector Photo Editor App & Category: PHOTOGRAPHY
App: Pic Collage - Photo Editor & Category: PHOTOGRAPHY
App: Photo Editor by Aviary & Category: PHOTOGRAPHY
App: Pixlr – Free Photo Editor & Category: PHOTOGRAPHY
App: Photo Editor & Category: PHOTOGRAPHY
App: Photo Collage Maker & Category: PHOTOGRAPHY
App: Cymera Camera- Photo Editor, Filter,Collage,Layout & Category: PHOTOGRAPHY
App: Adobe Photoshop Express:Photo Editor Collage Maker & Category: PHOTOGRAPHY
App: BeautyPlus - Easy Photo Editor & Selfie Camera & Category: PHOTOGRAPHY
App: PicsArt Photo Studio: Collage Maker & Pic Editor & Category: PHOTOGRAPHY
App: Photo Collage Editor & Category: PHOTOGRAPHY
App: InstaSize Photo Filters & Collage Editor & Category: PHOTOGRAPHY
App: Z Camera - Photo Editor, Beauty Selfie, Collage & Category: PHOTOGRAPHY
App: PhotoGrid: Video & Pic Collage Maker, Photo Editor & Category: PHOTOGRAPHY
App: Candy Camera - selfie, beauty camera, photo editor & Category: PHOTOGRAPHY
App: YouCam Perfect - Selfie Photo Editor & Category: PHOTOGRAPHY
App: Pixgram- video photo slideshow & Category: PHOTOGRAPHY
App: Fotor Photo Editor - Photo Collage & Photo Effects & Category: PHOTOGRAPHY
App: Camera360: Selfie Photo Editor with Funny Sticker & Category: PHOTOGRAPHY
App: Font Studio- Photo Texts Image & Category: PHOTOGRAPHY
App: Add Text To Photo & Category: PHOTOGRAPHY
App: Phonto - Text on Photos & Category: PHOTOGRAPHY
App: Shutterfly: Free Prints, Photo Books, Cards, Gifts & Category: PHOTOGRAPHY
App: Photo Collage - InstaMag & Category: PHOTOGRAPHY
App: BeautyPlus - Easy Photo Editor & Selfie Camera & Category: PHOTOGRAPHY
App: Meitu – Beauty Cam, Easy Photo Editor & Category: PHOTOGRAPHY
App: photo keypad lockscreen & Category: TOOLS
App: Keyboard - wallpapers , photos & Category: PERSONALIZATION
App: Photo Lock App - Hide Pictures & Videos & Category: PERSONALIZATION
App: Romantic Love Photo Frames & Category: PERSONALIZATION
App: Family Album Mitene: Private Photo & Video Sharing & Category: PARENTING
App: Photo Warp & Category: FAMILY
App: Arto: f.infrared photo & Category: PHOTOGRAPHY
App: Textgram - write on photos & Category: ART_AND_DESIGN
App: Keepsafe Photo Vault: Hide Private Photos & Videos & Category: PHOTOGRAPHY
App: PicsArt Photo Studio: Collage Maker & Pic Editor & Category: PHOTOGRAPHY
App: S Photo Editor - Collage Maker , Photo Collage & Category: PHOTOGRAPHY
App: VivaVideo - Video Editor & Photo Movie & Category: VIDEO_PLAYERS
App: B & W Filter for Photo Editor Pro & Category: PERSONALIZATION
App: Z Camera - Photo Editor, Beauty Selfie, Collage & Category: PHOTOGRAPHY
App: Six Pack Abs Photo Editor & Category: PHOTOGRAPHY
App: Photo Compress 2.0 - Ad Free & Category: TOOLS
App: Auto Dslr Photo Effect : Auto Focus Effect & Category: PHOTOGRAPHY
App: PhotoScan by Google Photos & Category: PHOTOGRAPHY
App: Blurfoto : Auto blur photo background & DSLR focus & Category: PHOTOGRAPHY
App: Google Photos & Category: PHOTOGRAPHY
App: iMediaShare – Photos & Music & Category: VIDEO_PLAYERS
App: Photo Editor by BeFunky & Category: PHOTOGRAPHY
App: BeautyPlus - Easy Photo Editor & Selfie Camera & Category: PHOTOGRAPHY
App: Be Fabulous PHOTO BOOTH & Category: PHOTOGRAPHY
App: Adobe Photoshop Fix & Category: PHOTOGRAPHY
App: BeFunky Photo Editor Pro & Category: PHOTOGRAPHY
App: Photo BG Changer & Category: PHOTOGRAPHY
App: PhotoLayers〜Superimpose,Eraser & Category: PHOTOGRAPHY
App: Blender BG - Photo Blend With Background & Category: PHOTOGRAPHY
App: Simple Photo BG Changer & Category: TOOLS
App: Change photo background & Category: PHOTOGRAPHY
App: Photo Background Changer 2018 - Blur Background & Category: LIFESTYLE
App: B&H Photo Video Pro Audio & Category: SHOPPING
App: DSLR Photography Training apps & Category: PHOTOGRAPHY
App: Photo Editor - BPhoto & Category: PHOTOGRAPHY
App: BK Photography & Category: PHOTOGRAPHY
App: Camera MX - Free Photo & Video Camera & Category: PHOTOGRAPHY
App: B&W Photo Filter Editor & Category: PHOTOGRAPHY
App: Photo Editor by Aviary & Category: PHOTOGRAPHY
App: Best CG Photography & Category: FAMILY
App: Gold Teeth Photo Editor & Category: PHOTOGRAPHY
App: QuickPic - Photo Gallery with Google Drive Support & Category: PHOTOGRAPHY
App: CV Maker for Job Applications:Photo Resume Builder & Category: TOOLS
App: Cymera Camera- Photo Editor, Filter,Collage,Layout & Category: PHOTOGRAPHY
App: LOCX Applock Lock Apps & Photo & Category: PRODUCTIVITY
App: Love Collage - Photo Editor & Category: PHOTOGRAPHY
App: LINE Camera - Photo editor & Category: PHOTOGRAPHY
App: DiskDigger photo recovery & Category: TOOLS
App: My Photo Keyboard & Category: PHOTOGRAPHY
App: Quik – Free Video Editor for photos, clips, music & Category: VIDEO_PLAYERS
App: Inst Download - Video & Photo & Category: VIDEO_PLAYERS
App: Best DP and Status (Daily Updates Photos) & Category: FAMILY
App: DP Photo Editor & Category: PHOTOGRAPHY
App: Fifa World Cup 2018: Photo Frame Editor & DP Maker & Category: PHOTOGRAPHY
App: DS photo & Category: VIDEO_PLAYERS
App: PhotoFrame for Synology DS & Category: PHOTOGRAPHY
App: DU Collage Maker - Photo Collage & Grid & Layout & Category: PHOTOGRAPHY
App: DV 2019 - EDV Photo & Form & Category: BOOKS_AND_REFERENCE
App: DV Lottery Photo & Category: VIDEO_PLAYERS
App: DV Lottery Photo Tool & Category: PHOTOGRAPHY
App: DV-2019 PHOTO TOOL & Category: FAMILY
App: Video Maker with Photo and Music & Category: PHOTOGRAPHY
App: Photo Lab Picture Editor: face effects, art frames & Category: PHOTOGRAPHY
App: A+ Gallery - Photos & Videos & Category: PHOTOGRAPHY
App: Beard Live Camera Photo Editor & Category: BEAUTY
App: FilterGrid - Cam&Photo Editor & Category: PHOTOGRAPHY
App: FB Photographie & Category: PHOTOGRAPHY
App: Download Facebook Photo Albums & Category: TOOLS
App: FD VR - Virtual Photo Gallery & Category: FAMILY
App: FG Autumn Photo Puzzle & Category: FAMILY
App: Ghost In Photo & Category: PHOTOGRAPHY
App: Life Made WI-Fi Touchscreen Photo Frame & Category: None
App: PIP Selfie Camera Photo Editor & Category: PHOTOGRAPHY
App: PIP-Camera FN Photo Effect & Category: PHOTOGRAPHY
App: Photo Editor Collage Maker Pro & Category: PHOTOGRAPHY
App: PhotoFunia & Category: PHOTOGRAPHY
App: Sad Poetry Photo Frames 2018 & Category: ART_AND_DESIGN
App: PTI Flex Maker, Photo Frame Editor & Songs 2018 & Category: EVENTS
App: Waterfall Photo Frames & Category: PHOTOGRAPHY
App: Photo frame & Category: PHOTOGRAPHY
App: Garden Photo Frames - Garden Photo Editor & Category: PHOTOGRAPHY
App: Photo Frame & Category: PHOTOGRAPHY
App: Night Photo Frame & Category: PHOTOGRAPHY
App: Kids Photo Frames & Category: PHOTOGRAPHY
App: Photo Frames & Category: PHOTOGRAPHY
App: Romantic Love Photo Frames & Category: PERSONALIZATION
App: Fifa World Cup 2018: Photo Frame Editor & DP Maker & Category: PHOTOGRAPHY
App: PhotoFrame for Synology DS & Category: PHOTOGRAPHY
App: Photo Lab Picture Editor: face effects, art frames & Category: PHOTOGRAPHY
App: Life Made WI-Fi Touchscreen Photo Frame & Category: None

In [33]:
cat

['COMICS',
 'DATING',
 'DATING',
 'EDUCATION',
 'EDUCATION',
 'EDUCATION',
 'EDUCATION',
 'EDUCATION',
 'ENTERTAINMENT',
 'ENTERTAINMENT',
 'ENTERTAINMENT',
 'EVENTS',
 'EVENTS',
 'LIBRARIES_AND_DEMO',
 'GAME',
 'FAMILY',
 'FAMILY',
 'FAMILY',
 'MEDICAL',
 'MEDICAL',
 'SHOPPING',
 'PRODUCTIVITY',
 'PARENTING',
 'FAMILY',
 'LIFESTYLE',
 'FAMILY',
 'FAMILY',
 'FAMILY',
 'BOOKS_AND_REFERENCE',
 'TOOLS',
 'TOOLS',
 'FAMILY',
 'HEALTH_AND_FITNESS',
 'FAMILY',
 'TOOLS',
 'NEWS_AND_MAGAZINES',
 'FAMILY',
 'TOOLS',
 'PRODUCTIVITY',
 'SOCIAL',
 'TOOLS',
 'VIDEO_PLAYERS',
 'SOCIAL',
 'GAME',
 'FAMILY',
 'NEWS_AND_MAGAZINES',
 'FAMILY',
 'FAMILY',
 'None',
 'LIFESTYLE',
 'FINANCE',
 'FOOD_AND_DRINK',
 'MEDICAL',
 'MEDICAL',
 'SHOPPING',
 'SHOPPING',
 'SHOPPING',
 'SHOPPING',
 'SHOPPING',
 'SHOPPING',
 'SHOPPING',
 'SHOPPING',
 'PARENTING',
 'SHOPPING',
 'BOOKS_AND_REFERENCE',
 'MEDICAL',
 'COMMUNICATION',
 'FAMILY',
 'None',
 'TOOLS',
 'TOOLS',
 'TOOLS',
 'COMMUNICATION',
 'TOOLS',
 'COMMUNICATION',
 'COMMUNICATION',
 'COMMUNICATION',
 'COMMUNICATION',
 'PRODUCTIVITY',
 'COMMUNICATION',
 'COMMUNICATION',
 'PRODUCTIVITY',
 'TOOLS',
 'TOOLS',
 'TOOLS',
 'TOOLS',
 'COMMUNICATION',
 'PRODUCTIVITY',
 'COMMUNICATION',
 'COMMUNICATION',
 'PERSONALIZATION',
 'None',
 'TOOLS',
 'TOOLS',
 'LIFESTYLE',
 'COMMUNICATION',
 'None',
 'ART_AND_DESIGN',
 'ART_AND_DESIGN',
 'ART_AND_DESIGN',
 'ART_AND_DESIGN',
 'ART_AND_DESIGN',
 'ART_AND_DESIGN',
 'ART_AND_DESIGN',
 'ART_AND_DESIGN',
 'ART_AND_DESIGN',
 'ART_AND_DESIGN',
 'BEAUTY',
 'BEAUTY',
 'BEAUTY',
 'COMICS',
 'DATING',
 'EVENTS',
 'EVENTS',
 'HEALTH_AND_FITNESS',
 'HEALTH_AND_FITNESS',
 'HOUSE_AND_HOME',
 'SOCIAL',
 'SOCIAL',
 'SOCIAL',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'TOOLS',
 'PERSONALIZATION',
 'PERSONALIZATION',
 'PERSONALIZATION',
 'PARENTING',
 'FAMILY',
 'PHOTOGRAPHY',
 'ART_AND_DESIGN',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'VIDEO_PLAYERS',
 'PERSONALIZATION',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'TOOLS',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'VIDEO_PLAYERS',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'TOOLS',
 'PHOTOGRAPHY',
 'LIFESTYLE',
 'SHOPPING',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'FAMILY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'TOOLS',
 'PHOTOGRAPHY',
 'PRODUCTIVITY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'TOOLS',
 'PHOTOGRAPHY',
 'VIDEO_PLAYERS',
 'VIDEO_PLAYERS',
 'FAMILY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'VIDEO_PLAYERS',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'BOOKS_AND_REFERENCE',
 'VIDEO_PLAYERS',
 'PHOTOGRAPHY',
 'FAMILY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'BEAUTY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'TOOLS',
 'FAMILY',
 'FAMILY',
 'PHOTOGRAPHY',
 'None',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'ART_AND_DESIGN',
 'EVENTS',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PERSONALIZATION',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'PHOTOGRAPHY',
 'None']

In [34]:
test = pd.DataFrame(cat, columns = ["category"])

In [35]:
test

            category
0             COMICS
1             DATING
2             DATING
3          EDUCATION
4          EDUCATION
..               ...
304  PERSONALIZATION
305      PHOTOGRAPHY
306      PHOTOGRAPHY
307      PHOTOGRAPHY
308             None

[309 rows x 1 columns]

In [36]:
test.value_counts()

category
PHOTOGRAPHY            155
TOOLS                   21
FAMILY                  20
ART_AND_DESIGN          12
COMMUNICATION           12
SHOPPING                11
VIDEO_PLAYERS            7
None                     6
PRODUCTIVITY             6
PERSONALIZATION          6
MEDICAL                  5
EDUCATION                5
SOCIAL                   5
EVENTS                   5
BEAUTY                   4
LIFESTYLE                4
BOOKS_AND_REFERENCE      3
DATING                   3
PARENTING                3
ENTERTAINMENT            3
HEALTH_AND_FITNESS       3
NEWS_AND_MAGAZINES       2
GAME                     2
COMICS                   2
LIBRARIES_AND_DEMO       1
FOOD_AND_DRINK           1
FINANCE                  1
HOUSE_AND_HOME           1
dtype: int64

In [37]:
# Based on the about hypothesis we will provide "PHOTOGRAPHY" value to Category column of row having index as 10472
mob.iloc[10472,1:2] = "PHOTOGRAPHY"

In [38]:
mob.iloc[10472]

App_name          Life Made WI-Fi Touchscreen Photo Frame
Category                                      PHOTOGRAPHY
Rating                                                1.9
Reviews                                              19.0
Size                                                 3.0M
Installs                                           1,000+
Type                                                 Free
Price                                                   0
Content Rating                                   Everyone
Genres                                                NaN
Last Updated                            February 11, 2018
Current Ver                                        1.0.19
Android Ver                                    4.0 and up
Name: 10472, dtype: object

In [39]:
mob.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App_name        10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10841 non-null  object
 9   Genres          10840 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10839 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [40]:
mob.Rating.describe()

count    9367.000000
mean        4.191513
std         0.515735
min         1.000000
25%         4.000000
50%         4.300000
75%         4.500000
max         5.000000
Name: Rating, dtype: float64

In [41]:
mob.Rating.mean()

4.191512757553112

In [42]:
# Fill all the null values of Rating column with the mean of Rating column
mob.Rating.fillna(mob.Rating.mean(), inplace = True)

In [43]:
mob.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App_name        10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          10841 non-null  float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10841 non-null  object
 9   Genres          10840 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10839 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [44]:
mob.Reviews

0           159
1           967
2         87510
3        215644
4           967
          ...
10836        38
10837         4
10838         3
10839       114
10840    398307
Name: Reviews, Length: 10841, dtype: object

In [45]:
# Converting the Reviews to int
mob.Reviews = mob.Reviews.astype(int)

In [46]:
mob.Reviews

0           159
1           967
2         87510
3        215644
4           967
          ...
10836        38
10837         4
10838         3
10839       114
10840    398307
Name: Reviews, Length: 10841, dtype: int64

In [47]:
mob.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App_name        10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          10841 non-null  float64
 3   Reviews         10841 non-null  int64
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10841 non-null  object
 9   Genres          10840 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10839 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 1.1+ MB

In [48]:
mob.Installs

0            10,000+
1           500,000+
2         5,000,000+
3        50,000,000+
4           100,000+
            ...
10836         5,000+
10837           100+
10838         1,000+
10839         1,000+
10840    10,000,000+
Name: Installs, Length: 10841, dtype: object

In [49]:
# Convert '5,000,000+' -> '5000000+' -> '5000000' -> 5000000 and datatype as int
mob.Installs = mob.Installs.str.replace(',','').str.rstrip('+').astype(int)

In [50]:
mob.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App_name        10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          10841 non-null  float64
 3   Reviews         10841 non-null  int64
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  int64
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10841 non-null  object
 9   Genres          10840 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10839 non-null  object
dtypes: float64(1), int64(2), object(10)
memory usage: 1.1+ MB

In [51]:
mob.Type

0        Free
1        Free
2        Free
3        Free
4        Free
         ...
10836    Free
10837    Free
10838    Free
10839    Free
10840    Free
Name: Type, Length: 10841, dtype: object

In [52]:
mob[mob.Type.isna()]

,App_name,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
9148,Command & Conquer: Rivals,FAMILY,4.191513,0,Varies with device,0,NaN,0,Everyone 10+,Strategy,"June 28, 2018",Varies with device,Varies with device

In [53]:
# By seeing that the Price is 0 for the 9148 row we can assign the Type as Free
mob.Type = mob.Type.replace(np.nan, "Free")

In [54]:
mob.Type.unique()

array(['Free', 'Paid'], dtype=object)

In [55]:
mob.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App_name        10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          10841 non-null  float64
 3   Reviews         10841 non-null  int64
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  int64
 6   Type            10841 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10841 non-null  object
 9   Genres          10840 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10839 non-null  object
dtypes: float64(1), int64(2), object(10)
memory usage: 1.1+ MB

In [56]:
mob.Price.unique()

array(['0', '$4.99', '$3.99', '$6.99', '$1.49', '$2.99', '$7.99', '$5.99',
       '$3.49', '$1.99', '$9.99', '$7.49', '$0.99', '$9.00', '$5.49',
       '$10.00', '$24.99', '$11.99', '$79.99', '$16.99', '$14.99',
       '$1.00', '$29.99', '$12.99', '$2.49', '$10.99', '$1.50', '$19.99',
       '$15.99', '$33.99', '$74.99', '$39.99', '$3.95', '$4.49', '$1.70',
       '$8.99', '$2.00', '$3.88', '$25.99', '$399.99', '$17.99',
       '$400.00', '$3.02', '$1.76', '$4.84', '$4.77', '$1.61', '$2.50',
       '$1.59', '$6.49', '$1.29', '$5.00', '$13.99', '$299.99', '$379.99',
       '$37.99', '$18.99', '$389.99', '$19.90', '$8.49', '$1.75',
       '$14.00', '$4.85', '$46.99', '$109.99', '$154.99', '$3.08',
       '$2.59', '$4.80', '$1.96', '$19.40', '$3.90', '$4.59', '$15.46',
       '$3.04', '$4.29', '$2.60', '$3.28', '$4.60', '$28.99', '$2.95',
       '$2.90', '$1.97', '$200.00', '$89.99', '$2.56', '$30.99', '$3.61',
       '$394.99', '$1.26', '$1.20', '$1.04'], dtype=object)

In [57]:
# Converting '$4.99' -> 4.99 and datatype of Price column to float
mob.Price = mob.Price.str.replace('$','').astype(float)

<ipython-input-57-aa67f360dbfc>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  mob.Price = mob.Price.str.replace('$','').astype(float)

In [58]:
mob.Price.unique()

array([  0.  ,   4.99,   3.99,   6.99,   1.49,   2.99,   7.99,   5.99,
         3.49,   1.99,   9.99,   7.49,   0.99,   9.  ,   5.49,  10.  ,
        24.99,  11.99,  79.99,  16.99,  14.99,   1.  ,  29.99,  12.99,
         2.49,  10.99,   1.5 ,  19.99,  15.99,  33.99,  74.99,  39.99,
         3.95,   4.49,   1.7 ,   8.99,   2.  ,   3.88,  25.99, 399.99,
        17.99, 400.  ,   3.02,   1.76,   4.84,   4.77,   1.61,   2.5 ,
         1.59,   6.49,   1.29,   5.  ,  13.99, 299.99, 379.99,  37.99,
        18.99, 389.99,  19.9 ,   8.49,   1.75,  14.  ,   4.85,  46.99,
       109.99, 154.99,   3.08,   2.59,   4.8 ,   1.96,  19.4 ,   3.9 ,
         4.59,  15.46,   3.04,   4.29,   2.6 ,   3.28,   4.6 ,  28.99,
         2.95,   2.9 ,   1.97, 200.  ,  89.99,   2.56,  30.99,   3.61,
       394.99,   1.26,   1.2 ,   1.04])

In [59]:
# Changing the column name
mob.rename(columns = {'Price':'Price($)'}, inplace = True)

In [60]:
mob['Content Rating']

0          Everyone
1          Everyone
2          Everyone
3              Teen
4          Everyone
            ...
10836      Everyone
10837      Everyone
10838      Everyone
10839    Mature 17+
10840      Everyone
Name: Content Rating, Length: 10841, dtype: object

In [61]:
mob['Content Rating'].unique()

array(['Everyone', 'Teen', 'Everyone 10+', 'Mature 17+',
       'Adults only 18+', 'Unrated'], dtype=object)

In [62]:
mob.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App_name        10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          10841 non-null  float64
 3   Reviews         10841 non-null  int64
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  int64
 6   Type            10841 non-null  object
 7   Price($)        10841 non-null  float64
 8   Content Rating  10841 non-null  object
 9   Genres          10840 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10839 non-null  object
dtypes: float64(2), int64(2), object(9)
memory usage: 1.1+ MB

In [63]:
mob.Genres

0                     Art & Design
1        Art & Design;Pretend Play
2                     Art & Design
3                     Art & Design
4          Art & Design;Creativity
                   ...
10836                    Education
10837                    Education
10838                      Medical
10839            Books & Reference
10840                    Lifestyle
Name: Genres, Length: 10841, dtype: object

In [64]:
mob.Genres.unique()

array(['Art & Design', 'Art & Design;Pretend Play',
       'Art & Design;Creativity', 'Art & Design;Action & Adventure',
       'Auto & Vehicles', 'Beauty', 'Books & Reference', 'Business',
       'Comics', 'Comics;Creativity', 'Communication', 'Dating',
       'Education;Education', 'Education', 'Education;Creativity',
       'Education;Music & Video', 'Education;Action & Adventure',
       'Education;Pretend Play', 'Education;Brain Games', 'Entertainment',
       'Entertainment;Music & Video', 'Entertainment;Brain Games',
       'Entertainment;Creativity', 'Events', 'Finance', 'Food & Drink',
       'Health & Fitness', 'House & Home', 'Libraries & Demo',
       'Lifestyle', 'Lifestyle;Pretend Play',
       'Adventure;Action & Adventure', 'Arcade', 'Casual', 'Card',
       'Casual;Pretend Play', 'Action', 'Strategy', 'Puzzle', 'Sports',
       'Music', 'Word', 'Racing', 'Casual;Creativity',
       'Casual;Action & Adventure', 'Simulation', 'Adventure', 'Board',
       'Trivia', 'Role Playing', 'Simulation;Education',
       'Action;Action & Adventure', 'Casual;Brain Games',
       'Simulation;Action & Adventure', 'Educational;Creativity',
       'Puzzle;Brain Games', 'Educational;Education', 'Card;Brain Games',
       'Educational;Brain Games', 'Educational;Pretend Play',
       'Entertainment;Education', 'Casual;Education',
       'Music;Music & Video', 'Racing;Action & Adventure',
       'Arcade;Pretend Play', 'Role Playing;Action & Adventure',
       'Simulation;Pretend Play', 'Puzzle;Creativity',
       'Sports;Action & Adventure', 'Educational;Action & Adventure',
       'Arcade;Action & Adventure', 'Entertainment;Action & Adventure',
       'Puzzle;Action & Adventure', 'Strategy;Action & Adventure',
       'Music & Audio;Music & Video', 'Health & Fitness;Education',
       'Adventure;Education', 'Board;Brain Games',
       'Board;Action & Adventure', 'Board;Pretend Play',
       'Casual;Music & Video', 'Role Playing;Pretend Play',
       'Entertainment;Pretend Play', 'Video Players & Editors;Creativity',
       'Card;Action & Adventure', 'Medical', 'Social', 'Shopping',
       'Photography', 'Travel & Local',
       'Travel & Local;Action & Adventure', 'Tools', 'Tools;Education',
       'Personalization', 'Productivity', 'Parenting',
       'Parenting;Music & Video', 'Parenting;Education',
       'Parenting;Brain Games', 'Weather', 'Video Players & Editors',
       'Video Players & Editors;Music & Video', 'News & Magazines',
       'Maps & Navigation', 'Health & Fitness;Action & Adventure',
       'Educational', 'Casino', 'Adventure;Brain Games',
       'Trivia;Education', 'Lifestyle;Education',
       'Books & Reference;Creativity', 'Books & Reference;Education',
       'Puzzle;Education', 'Role Playing;Education',
       'Role Playing;Brain Games', 'Strategy;Education',
       'Racing;Pretend Play', 'Communication;Creativity', nan,
       'Strategy;Creativity'], dtype=object)

In [65]:
mob[mob.Genres.isna()]

,App_name,Category,Rating,Reviews,Size,Installs,Type,Price($),Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,PHOTOGRAPHY,1.9,19,3.0M,1000,Free,0.0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up

In [66]:
mob.Category.unique()

array(['ART_AND_DESIGN', 'AUTO_AND_VEHICLES', 'BEAUTY',
       'BOOKS_AND_REFERENCE', 'BUSINESS', 'COMICS', 'COMMUNICATION',
       'DATING', 'EDUCATION', 'ENTERTAINMENT', 'EVENTS', 'FINANCE',
       'FOOD_AND_DRINK', 'HEALTH_AND_FITNESS', 'HOUSE_AND_HOME',
       'LIBRARIES_AND_DEMO', 'LIFESTYLE', 'GAME', 'FAMILY', 'MEDICAL',
       'SOCIAL', 'SHOPPING', 'PHOTOGRAPHY', 'SPORTS', 'TRAVEL_AND_LOCAL',
       'TOOLS', 'PERSONALIZATION', 'PRODUCTIVITY', 'PARENTING', 'WEATHER',
       'VIDEO_PLAYERS', 'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION'],
      dtype=object)

In [67]:
b = ["PHOTOGRAPHY"]
g = []
for i in b:
  for j,k in zip(mob.Category, mob.Genres):
    if i == j:
      print(f'Category: {j} & Genres: {k}')
      g.append(str(k))

Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: nan
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography
Category: PHOTOGRAPHY & Genres: Photography

In [68]:
g

['Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'nan',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography',
 'Photography']

In [69]:
test = pd.DataFrame(g, columns = ['Genres'])

In [70]:
test.value_counts()

Genres
Photography    335
nan              1
dtype: int64

In [71]:
# Based on the above hypothesis we can say that the App that has the Category as Photography will also have the Genres as Photography
# So assigning the Genres value as "Photography" to nan value of Genres column which has the Category as Photography
mob.Genres = mob.Genres.replace(np.nan, "Photography")

In [72]:
# Changing the column name
mob.rename(columns={'Last Updated':'Last_Updated'}, inplace = True)
mob.rename(columns={'Current Ver':'Current_Ver'}, inplace = True)
mob.rename(columns={'Android Ver':'Android_Ver'}, inplace = True)

In [73]:
mob.Last_Updated

0         January 7, 2018
1        January 15, 2018
2          August 1, 2018
3            June 8, 2018
4           June 20, 2018
               ...
10836       July 25, 2017
10837        July 6, 2018
10838    January 20, 2017
10839    January 19, 2015
10840       July 25, 2018
Name: Last_Updated, Length: 10841, dtype: object

In [74]:
''' Convert into
DAY, MONTH, YEAR
7      1    2018
'''
mob.Last_Updated = pd.to_datetime(mob.Last_Updated)
mob['Day'] = mob.Last_Updated.dt.day
mob['Months'] = mob.Last_Updated.dt.month
mob['Year'] = mob.Last_Updated.dt.year
mob.drop('Last_Updated',axis = 1, inplace = True)

In [75]:
mob.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App_name        10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          10841 non-null  float64
 3   Reviews         10841 non-null  int64
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  int64
 6   Type            10841 non-null  object
 7   Price($)        10841 non-null  float64
 8   Content Rating  10841 non-null  object
 9   Genres          10841 non-null  object
 10  Current_Ver     10833 non-null  object
 11  Android_Ver     10839 non-null  object
 12  Day             10841 non-null  int64
 13  Months          10841 non-null  int64
 14  Year            10841 non-null  int64
dtypes: float64(2), int64(5), object(8)
memory usage: 1.2+ MB

In [76]:
new = mob.Android_Ver.copy()

In [77]:
new

0              4.0.3 and up
1              4.0.3 and up
2              4.0.3 and up
3                4.2 and up
4                4.4 and up
                ...
10836            4.1 and up
10837            4.1 and up
10838            2.2 and up
10839    Varies with device
10840    Varies with device
Name: Android_Ver, Length: 10841, dtype: object

Convert the values of Android_Ver as

*   '4.0.3' -> 4.0

    '4.4' -> 4.4

In [78]:
re.sub(' .*', '', "4.0.3 and up")

'4.0.3'

In [79]:
l=[]
for i in new:
  if i != "Varies with device":
    a=re.sub(' .*', '', str(i))
    l.append(a)
  elif i == "Varies with device":
    l.append("Varies with device")

In [80]:
l

['4.0.3',
 '4.0.3',
 '4.0.3',
 '4.2',
 '4.4',
 '2.3',
 '4.0.3',
 '4.2',
 '3.0',
 '4.0.3',
 '4.1',
 '4.0',
 '4.1',
 '4.4',
 '2.3',
 '4.2',
 '4.1',
 '2.3',
 '4.0.3',
 '4.1',
 '4.1',
 '4.0.3',
 '4.0.3',
 '4.1',
 '4.1',
 '3.0',
 '4.0.3',
 '4.0.3',
 '2.3',
 '2.3',
 '4.0.3',
 '2.3',
 '4.0',
 '4.1',
 '4.1',
 '4.1',
 '4.4',
 '2.3.3',
 '4.0.3',
 '4.0',
 '4.0.3',
 '4.0.3',
 'Varies with device',
 '4.1',
 '4.1',
 '4.1',
 '4.1',
 '4.1',
 '2.3',
 '4.0.3',
 '4.1',
 '4.1',
 'Varies with device',
 '4.1',
 '4.1',
 '4.0',
 '4.4',
 '4.1',
 '2.2',
 '4.4',
 '4.0.3',
 '4.2',
 '4.1',
 '4.0',
 '4.2',
 '4.4',
 '2.3',
 'Varies with device',
 'Varies with device',
 '4.0.3',
 '4.0.3',
 '4.2',
 '5.0',
 '2.3.3',
 '4.0',
 '4.0',
 '4.1',
 '4.0',
 '4.1',
 '4.1',
 '6.0',
 '4.2',
 '5.0',
 '4.0.3',
 '4.4',
 'Varies with device',
 '2.3',
 '4.0.3',
 'Varies with device',
 'Varies with device',
 '4.1',
 '4.0.3',
 '4.0.3',
 '4.0.3',
 '4.0.3',
 '4.0',
 '4.0.3',
 '4.0',
 '5.0',
 '4.1',
 '4.1',
 '4.0.3',
 'Varies with device',
 '4.1',
 '4.0.3',
 '4.0',
 '4.2',
 '5.0',
 '4.0.3',
 'Varies with device',
 '4.0',
 '4.0',
 '4.0.3',
 '3.0',
 '4.0.3',
 '4.0.3',
 '4.0.3',
 'Varies with device',
 '4.0',
 '4.0',
 '4.0.3',
 '4.0',
 '5.0',
 '4.1',
 '4.0.3',
 '4.0',
 '4.1',
 '4.1',
 '4.0',
 '2.3',
 '3.0',
 '4.0.3',
 '4.0.3',
 '1.6',
 '3.0',
 '4.0.3',
 '4.0',
 '4.0.3',
 '4.0.3',
 'Varies with device',
 '4.4',
 '4.0',
 'Varies with device',
 'Varies with device',
 '1.5',
 'Varies with device',
 'Varies with device',
 '4.1',
 '4.0',
 'Varies with device',
 '4.0',
 '4.0.3',
 'Varies with device',
 '2.3',
 '4.0.3',
 '4.1',
 '4.0.3',
 'Varies with device',
 '4.1',
 '4.1',
 '2.3',
 '4.1',
 'Varies with device',
 '2.3',
 '4.0',
 '4.0',
 '4.1',
 '4.0.3',
 '3.0',
 '4.0.3',
 '2.1',
 '4.4',
 'Varies with device',
 '7.0',
 '4.0',
 '4.0.3',
 '4.0.3',
 '3.0',
 '3.0',
 'Varies with device',
 '6.0',
 '4.0',
 '4.2',
 '4.0.3',
 '2.2',
 '5.1',
 '4.2',
 'Varies with device',
 'Varies with device',
 'Varies with device',
 '5.0',
 'Varies with device',
 'Varies with device',
 '4.4',
 '4.1',
 '4.0.3',
 '5.0',
 '4.1',
 '4.1',
 '4.0.3',
 '1.5',
 'Varies with device',
 'Varies with device',
 '4.3',
 'Varies with device',
 '4.1',
 '4.0',
 'Varies with device',
 'Varies with device',
 '2.2',
 '4.1',
 'Varies with device',
 '4.1',
 '4.0',
 'Varies with device',
 '4.1',
 '4.0',
 '4.1',
 '4.2',
 '4.0',
 '4.0',
 '4.0.3',
 '4.0.3',
 '2.2',
 '4.0.3',
 '7.0',
 'Varies with device',
 '6.0',
 'Varies with device',
 '4.0.3',
 'Varies with device',
 '3.0',
 '4.1',
 '4.1',
 '4.0',
 '3.0',
 'Varies with device',
 '4.1',
 '4.0.3',
 '4.4',
 'Varies with device',
 '4.2',
 '5.0',
 '4.1',
 '4.1',
 'Varies with device',
 '5.0',
 '4.0.3',
 '5.0',
 '4.4',
 '4.0',
 '4.1',
 '4.1',
 '4.4',
 '4.1',
 '4.3',
 '4.0',
 '5.0',
 '4.4',
 'Varies with device',
 '4.0.3',
 '4.4',
 '4.0',
 '5.0',
 'Varies with device',
 'Varies with device',
 '4.1',
 '4.0.3',
 '4.4',
 'Varies with device',
 '4.2',
 '5.0',
 '4.1',
 '4.1',
 'Varies with device',
 '5.0',
 '4.0.3',
 '5.0',
 '4.4',
 '4.0',
 '4.1',
 '4.1',
 '4.4',
 '4.1',
 'Varies with device',
 '4.0.3',
 'Varies with device',
 '3.0',
 '4.1',
 '4.1',
 '4.0',
 '3.0',
 'Varies with device',
 '4.1',
 'Varies with device',
 '5.0',
 '4.1',
 'Varies with device',
 '4.1',
 '4.1',
 '4.0.3',
 '4.4',
 '4.1',
 '4.1',
 '5.0',
 '4.0',
 '2.3',
 '4.0.3',
 '4.2',
 '4.0.3',
 '4.0.3',
 '4.0.3',
 '4.0.3',
 '4.0.3',
 '4.1',
 'Varies with device',
 '4.2',
 '4.4',
 '4.4',
 '4.0',
 'Varies with device',
 '4.2',
 '4.1',
 '4.1',
 '5.0',
 '4.0.3',
 '4.1',
 'Varies with device',
 '4.0',
 '4.0.3',
 '2.3',
 '4.0.3',
 '4.0.3',
 '4.0',
 '4.4',
 'Varies with device',
 'Varies with device',
 '4.1',
 'Varies with device',
 '2.3',
 'Varies with device',
 'Varies with device',
 'Varies with device',
 '4.4',
 'Varies with device',
 '4.4',
 '4.0',
 '4.0',
 '5.0',
 '4.1',
 '4.0.3',
 'Varies with device',
 '4.0.3',
 'Varies with device',
 'Varies with device',
 '4.1',
 'Varies with device',
 '4.1',
 '5.0',
 'Varies with device',
 'Varies with device',
 'Varies with device',
 '4.0.3',
 'Varies with device',
 '4.0.3',
 'Varies with device',
 '4.0',
 '4.0.3',
 '5.0',
 'Varies with device',
 'Varies with device',
 '4.4',
 '4.1',
 'Varies with device',
 '4.1',
 'Varies with device',
 'Varies with device',
 '4.0.3',
 '4.0',
 '4.3',
 '4.4',
 'Varies with device',
 'Varies with device',
 '4.0',
 '4.0.3',
 'Varies with device',
 'Varies with device',
 '4.2',
 '4.0',
 '4.4',
 'Varies with device',
 'Varies with device',
 'Varies with device',
 'Varies with device',
 'Varies with device',
 '4.0',
 'Varies with device',
 '2.3',
 '2.3',
 'Varies with device',
 '4.0.3',
 '4.1',
 'Varies with device',
 'Varies with device',
 'Varies with device',
 '4.0.3',
 '4.0.3',
 'Varies with device',
 '5.0',
 '4.0',
 '4.1',
 'Varies with device',
 'Varies with device',
 '4.0',
 '4.1',
 'Varies with device',
 '2.3',
 'Varies with device',
 'Varies with device',
 '4.0',
 '4.0',
 '4.0.3',
 'Varies with device',
 '4.0',
 '4.0',
 '4.0',
 '3.0',
 '4.1',
 '4.0.3',
 '2.1',
 '4.0',
 'Varies with device',
 '4.0',
 '4.0',
 '4.0.3',
 '5.0',
 '4.0.3',
 '5.0',
 '4.0',
 '2.1',
 '4.1',
 '4.1',
 'Varies with device',
 'Varies with device',
 '4.1',
 'Varies with device',
 '4.0.3',
 '4.1',
 'Varies with device',
 'Varies with device',
 '2.3',
 'Varies with device',
 '4.4',
 '4.0.3',
 'Varies with device',
 '4.1',
 '4.1',
 '5.0',
 '2.0',
 'Varies with device',
 '2.2',
 '4.0',
 'Varies with device',
 'Varies with device',
 'Varies with device',
 '4.0',
 '4.4',
 'Varies with device',
 'Varies with device',
 'Varies with device',
 '2.3.3',
 '4.0.3',
 'Varies with device',
 'Varies with device',
 'Varies with device',
 'Varies with device',
 '4.1',
 '4.0',
 '4.0',
 '4.0',
 '4.0.3',
 '4.0',
 'Varies with device',
 '4.1',
 'Varies with device',
 '4.1',
 '5.0',
 '4.1',
 '4.1',
 '4.1',
 '4.4',
 'Varies with device',
 '4.1',
 '4.0',
 '4.4',
 '4.1',
 '4.4',
 '4.1',
 '4.1',
 '4.1',
 'Varies with device',
 '4.2',
 '4.1',
 '4.1',
 '4.4',
 '4.1',
 '4.4',
 '4.1',
 'Varies with device',
 '4.0.3',
 '4.2',
 '4.0.3',
 '4.0.3',
 '4.4',
 '4.0',
 '4.1',
 '4.0.3',
 '4.1',
 '5.0',
 '4.4',
 '4.0.3',
 '4.1',
 '5.0',
 '4.1',
 '4.0',
 '4.0.3',
 '4.0',
 '4.1',
 '4.0.3',
 '4.0',
 '4.0.3',
 '4.2',
 'Varies with device',
 '4.1',
 '4.0.3',
 '4.0.3',
 '5.0',
 '4.0',
 '4.1',
 '4.1',
 '4.1',
 '4.1',
 '4.1',
 '4.4',
 '4.1',
 '5.0',
 '4.4',
 '4.1',
 '4.1',
 '4.0.3',
 '4.1',
 '4.1',
 '4.1',
 'Varies with device',
 '5.0',
 '5.0',
 '4.1',
 '4.0.3',
 '4.0.3',
 '4.2',
 '4.4',
 'Varies with device',
 '4.1',
 '4.2',
 '4.1',
 '4.1',
 '4.1',
 '4.3',
 '4.1',
 '4.0.3',
 '4.1',
 '4.1',
 '4.0.3',
 '4.1',
 'Varies with device',
 '4.0.3',
 '4.1',
 '4.1',
 '4.2',
 '4.0.3',
 '4.1',
 '4.0.3',
 '4.1',
 '4.2',
 '4.1',
 '4.1',
 '4.0.3',
 '4.1',
 '4.0.3',
 '4.1',
 '4.0',
 '4.1',
 '4.0.3',
 '4.1',
 '4.1',
 '4.0.3',
 '4.0.3',
 '4.0.3',
 '4.2',
 '4.0',
 '4.1',
 '4.0',
 '4.4',
 '4.3',
 '4.0.3',
 '4.0.3',
 '4.0.3',
 '4.0.3',
 '4.0.3',
 '4.0.3',
 '4.0.3',
 '4.4',
 '4.0.3',
 '4.0',
 '4.0.3',
 '4.4',
 '4.0.3',
 '4.0',
 '4.0.3',
 '4.0.3',
 '4.0.3',
 '4.0',
 '4.1',
 '4.1',
 '4.0.3',
 '4.0.3',
 '4.0.3',
 '4.0.3',
 '3.0',
 '4.0',
 '4.1',
 '4.4',
 '4.1',
 '4.0.3',
 '4.0.3',
 '4.4',
 '4.0.3',
 '4.0.3',
 '4.0.3',
 '4.0.3',
 '4.0.3',
 '4.1',
 '4.1',
 '4.0',
 '4.0.3',
 '4.0.3',
 '4.0',
 '3.0',
 '4.0.3',
 '4.0.3',
 '4.2',
 '4.1',
 '4.2',
 '4.1',
 '4.1',
 '4.1',
 '5.0',
 '4.0.3',
 '4.0.3',
 '4.0',
 '4.0.3',
 '4.0.3',
 '4.2',
 '5.0',
 '4.1',
 '4.3',
 '4.0.3',
 '4.4',
 '4.4',
 '4.0.3',
 'Varies with device',
 '4.0.3',
 '4.0.3',
 '4.0.3',
 '4.1',
 '4.0.3',
 '4.4',
 '4.1',
 '4.4',
 '4.1',
 '4.0.3',
 '4.0.3',
 '4.0.3',
 '4.0',
 '4.1',
 '4.0.3',
 '4.0.3',
 '4.0.3',
 '4.0.3',
 '4.0.3',
 '4.0',
 '4.4',
 '4.0.3',
 '4.0',
 '4.1',
 '4.1',
 '4.2',
 '4.0.3',
 '4.0.3',
 'Varies with device',
 '4.1',
 '4.0',
 '4.1',
 '4.0',
 '4.0',
 '4.0',
 '4.0',
 '4.0.3',
 '4.0',
 '4.0',
 '4.1',
 '4.1',
 '4.2',
 'Varies with device',
 'Varies with device',
 '4.0',
 '4.0',
 '4.4',
 '4.0',
 '2.3',
 '4.1',
 '5.0',
 '1.6',
 '4.4',
 'Varies with device',
 '4.0.3',
 '2.3',
 '4.2',
 '4.4',
 '2.3',
 '4.1',
 '4.1',
 '2.3',
 '4.1',
 'Varies with device',
 '4.0.3',
 '4.1',
 'Varies with device',
 '4.1',
 '4.1',
 'Varies with device',
 '5.0',
 'Varies with device',
 '4.1',
 'Varies with device',
 '4.0.3',
 'Varies with device',
 '5.0',
 '4.1',
 '4.1',
 'Varies with device',
 'Varies with device',
 '4.0',
 '2.3',
 '2.3',
 '2.3',
 '5.0',
 '5.0',
 '4.0',
 'Varies with device',
 '4.0',
 '4.0',
 '4.0',
 '4.1',
 '4.0',
 '4.4',
 '4.1',
 '4.4',
 '2.2',
 '2.3.3',
 '2.1',
 'Varies with device',
 '2.3.3',
 '4.0',
 'Varies with device',
 '2.1',
 '4.1',
 'Varies with device',
 '4.0',
 'Varies with device',
 'Varies with device',
 'Varies with device',
 '4.1',
 '4.1',
 'Varies with device',
 'Varies with device',
 'Varies with device',
 '5.0',
 '5.0',
 '4.1',
 '5.0',
 'Varies with device',
 '4.1',
 'Varies with device',
 'Varies with device',
 '4.4',
 '4.4',
 'Varies with device',
 '4.1',
 'Varies with device',
 '4.0',
 '5.0',
 '4.4',
 '4.2',
 '4.1',
 '4.0',
 'Varies with device',
 '4.0',
 '5.0',
 'Varies with device',
 '2.3',
 '4.0.3',
 '4.0',
 '2.3',
 'Varies with device',
 '4.0.3',
 '2.3',
 '4.0',
 'Varies with device',
 'Varies with device',
 '4.0.3',
 '3.2',
 '4.4',
 'Varies with device',
 'Varies with device',
 '4.1',
 'Varies with device',
 '3.0',
 '4.0',
 '4.1',
 '4.2',
 '5.0',
 'Varies with device',
 '4.4',
 '3.0',
 '5.0',
 'Varies with device',
 '4.4',
 'Varies with device',
 'Varies with device',
 '4.1',
 '4.0',
 'Varies with device',
 '4.1',
 '4.1',
 'Varies with device',
 '5.0',
 '5.0',
 '4.0.3',
 '4.1',
 '4.1',
 '4.0.3',
 '4.1',
 '4.4',
 '4.4',
 'Varies with device',
 '4.0.3',
 'Varies with device',
 '4.1',
 '4.1',
 '5.0',
 'Varies with device',
 '6.0',
 '4.2',
 '4.0.3',
 'Varies with device',
 'Varies with device',
 'Varies with device',
 '4.0',
 'Varies with device',
 '2.3.3',
 '4.0.3',
 '4.1',
 'Varies with device',
 '4.1',
 'Varies with device',
 '4.2',
 '4.2',
 'Varies with device',
 '4.1',
 '4.1',
 '4.1',
 '4.0.3',
 '4.4',
 '4.1',
 'Varies with device',
 '4.1',
 '4.4',
 'Varies with device',
 'Varies with device',
 '4.3',
 '4.1',
 '4.1',
 '4.1',
 'Varies with device',
 '4.2',
 '5.0',
 'Varies with device',
 '4.4',
 'Varies with device',
 '6.0',
 '4.1',
 '5.0',
 'Varies with device',
 'Varies with device',
 'Varies with device',
 'Varies with device',
 '4.1',
 'Varies with device',
 '4.4',
 'Varies with device',
 '4.1',
 'Varies with device',
 '4.1',
 'Varies with device',
 '4.4',
 '4.4',
 '4.4',
 '4.4',
 '4.4',
 '4.4',
 '4.4',
 '4.4',
 '5.0',
 'Varies with device',
 'Varies with device',
 'Varies with device',
 '4.4',
 '4.0.3',
 '4.4',
 'Varies with device',
 'Varies with device',
 '4.1',
 'Varies with device',
 'Varies with device',
 'Varies with device',
 '4.1',
 '4.4',
 '5.0',
 '4.4',
 '4.4',
 '4.4',
 '4.1',
 '4.4',
 'Varies with device',
 '4.1',
 '4.4',
 '4.4',
 '4.4',
 '4.4',
 '4.4',
 '4.4',
 '5.0',
 '4.1',
 'Varies with device',
 'Varies with device',
 '4.4',
 '4.4',
 'Varies with device',
 '4.1',
 'Varies with device',
 'Varies with device',
 'Varies with device',
 '4.4',
 'Varies with device',
 '5.0',
 'Varies with device',
 '4.4',
 '4.4',
 'Varies with device',
 '4.4',
 'Varies with device',
 '4.4',
 '5.0',
 'Varies with device',
 'Varies with device',
 '4.3',
 '4.4',
 '4.4',
 'Varies with device',
 '4.4',
 '4.4',
 '4.4',
 '4.4',
 '4.4',
 '4.4',
 '4.4',
 '4.2',
 'Varies with device',
 'Varies with device',
 '6.0',
 '4.0.3',
 '4.4',
 'Varies with device',
 '5.0',
 'Varies with device',
 'Varies with device',
 '4.0',
 '2.3.3',
 '2.3',
 ...]

In [81]:
test = pd.DataFrame(l, columns = ["Android_Ver"])
test.value_counts()

Android_Ver
4.1                   2452
4.0.3                 1503
4.0                   1376
Varies with device    1362
4.4                    980
2.3                    652
5.0                    605
4.2                    394
2.3.3                  281
2.2                    245
4.3                    243
3.0                    241
2.1                    134
1.6                    116
6.0                     60
7.0                     43
3.2                     36
2.0                     32
5.1                     24
1.5                     20
4.4W                    12
3.1                     10
2.0.1                    7
8.0                      6
7.1                      3
1.0                      2
nan                      2
dtype: int64

In [82]:
# Based on the above hypothesis we can replace the value "Varies with device" to "4.1"
test = test.replace("Varies with device", "4.1")

In [83]:
test.value_counts()

Android_Ver
4.1            3814
4.0.3          1503
4.0            1376
4.4             980
2.3             652
5.0             605
4.2             394
2.3.3           281
2.2             245
4.3             243
3.0             241
2.1             134
1.6             116
6.0              60
7.0              43
3.2              36
2.0              32
5.1              24
1.5              20
4.4W             12
3.1              10
2.0.1             7
8.0               6
7.1               3
1.0               2
nan               2
dtype: int64

In [84]:
test

      Android_Ver
0           4.0.3
1           4.0.3
2           4.0.3
3             4.2
4             4.4
...           ...
10836         4.1
10837         4.1
10838         2.2
10839         4.1
10840         4.1

[10841 rows x 1 columns]

In [85]:
# Taking only firts 3 characters
for i in test.Android_Ver:
  a = i[0:3]
  test.Android_Ver = test.Android_Ver.replace(i,a)

In [86]:
test

      Android_Ver
0             4.0
1             4.0
2             4.0
3             4.2
4             4.4
...           ...
10836         4.1
10837         4.1
10838         2.2
10839         4.1
10840         4.1

[10841 rows x 1 columns]

In [87]:
# Assigning the clean data values to the original dataframe
mob.Android_Ver = test

In [88]:
mob.Android_Ver

0        4.0
1        4.0
2        4.0
3        4.2
4        4.4
        ...
10836    4.1
10837    4.1
10838    2.2
10839    4.1
10840    4.1
Name: Android_Ver, Length: 10841, dtype: object

In [89]:
mob.head()

,App_name,Category,Rating,Reviews,Size,Installs,Type,Price($),Content Rating,Genres,Current_Ver,Android_Ver,Day,Months,Year
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,10000,Free,0.0,Everyone,Art & Design,1.0.0,4.0,7,1,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2.0.0,4.0,15,1,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,5000000,Free,0.0,Everyone,Art & Design,1.2.4,4.0,1,8,2018
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,50000000,Free,0.0,Teen,Art & Design,Varies with device,4.2,8,6,2018
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,100000,Free,0.0,Everyone,Art & Design;Creativity,1.1,4.4,20,6,2018

# Now the data is clean and you can carry out some more Analysis.....!